name: 'Octo my README'
author: 'arndom'
description: 'add custom octocat based on most used language to readme'

inputs:
  user:  # id of input
    description: 'greet the user'
    required: true
    default: 'World'
  readme_path:
    description: 'Comma separated paths of the readme files you want to update'
    default: './README.md'
    required: false

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'

runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'activity'
  color: 'blue'