name: 'Octo my README'
author: 'arndom'
description: 'Add OctoCat based on most used language to README'

inputs:
  gh_token:
    description: 'user token'
    required: true
    default: ${{ github.token }}
outputs:
  result:
    description: 'the result of all this'

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'activity'
  color: 'blue'